version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - business-db:/var/lib/postgresql/data

  business:
    build:
      context: .
    environment:
      PORT: 3000
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: postgres
      DB_NAME: postgres
      DB_DIALECT: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  business-db: